### ISSUE TITLE
"Place of Death" --> "Location of death"

### ISSUE THREAD

**Issue by saulakravitz** [nightingaleproject/vrdr-dotnet#355]
The display name for LOINC code 58332-8 is incorrect ("Place of Death").  Should be "Location of Death".
https://loinc.org/search/?t=1&s=58332-8

Line 5402 of VRDR/DeathRecord_submissionProperties.cs

**Comment by johnarleyburns** [comment]
incorporated into changes for issue #359, so closing this separate issue.
