### ISSUE TITLE
The display names for the elements of vrdr-input-race-and-ethnicity are wrong

### ISSUE THREAD

**Issue by saulakravitz** [nightingaleproject/vrdr-dotnet#358]
The display names for the coded components of http://build.fhir.org/ig/HL7/vrdr/branches/master/StructureDefinition-vrdr-input-race-and-ethnicity.html are supposed to be those defined in http://build.fhir.org/ig/HL7/vrdr/branches/master/CodeSystem-vrdr-component-cs.html.   So, for the component with code 'HispanicMexican' the display name for the code is 'Hispanic Mexican'.   Currently both the code and the display are HispanicMexican.  Here is an example.

{
                  "code": {
                    "coding": [
                      {
                        "system": "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-component-cs",
                        "code": "GuamanianOrChamorro",
                        "display": "GuamanianOrChamorro"
                      }
                    ]
                  },
   Should be:
   
   {
                  "code": {
                    "coding": [
                      {
                        "system": "http://hl7.org/fhir/us/vrdr/CodeSystem/vrdr-component-cs",
                        "code": "GuamanianOrChamorro",
                        "display": "Guamanian Or Chamorro"
                      }
                    ]
                  },

The root of the problem is two fold:
  1) proximate:  at DeathRecord_submissionProperties.cs: 2653
      component.Code = new CodeableConcept(CodeSystems.ComponentCode, element.Item1, element.Item1, null);
      both the code and the display value are set to the same value (element.item1).
  2) Unlike ValueSets.cs, there is no mapping table for CodeSystems.   Probably worth adding a similar mechanism, driven from the IG, that would be updated via script when/if the VRDR IG changes.

**Comment by johnarleyburns** [comment]
Incorporated into changes for issue 359.
