### ISSUE TITLE
Fix issues with Connectathon records

### ISSUE THREAD

**Issue by smacadam** [nightingaleproject/vrdr-dotnet#359]
After fixes are made in the library, Canary should be rebuilt

In the Twila Hilty Connectathon example

0) Patient.gender is missing (required by USCore)
1) DeathCertificateDocument (Composition) lacks date field
2) generated valueTime from Canary is incorrect in DeathDate

"valueTime": "10:00" ==> "10:00:00"

```json
{
"resourceType": "Observation",
"id": "a06dc671-f09d-4a3f-ab7e-900173e96110",
"meta":

{ "profile": [ "http://hl7.org/fhir/us/vrdr/StructureDefinition/vrdr-death-date" ] }

,
"status": "final",
"code": {
"coding": [

{ "system": "http://loinc.org", "code": "81956-5", "display": "Date+time of death" }

]
},
"subject":

{ "reference": "urn:uuid:4246ad39-25e4-4eee-82b7-1d11829a7eff" }

,
"_valueDateTime": {
"extension": [
{
"extension": [


{ "url": "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Year", "valueUnsignedInt": 2022 }

,


{ "url": "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Month", "valueUnsignedInt": 1 }

,


{ "url": "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Day", "valueUnsignedInt": 10 }

,

{ "url": "http://hl7.org/fhir/us/vrdr/StructureDefinition/Date-Time", "valueTime": "10:00" }

],
"url": "http://hl7.org/fhir/us/vrdr/StructureDefinition/PartialDateTime"
}
]
},
"component": [
{
"code": {
"coding": [

{ "system": "http://loinc.org", "code": "58332-8", "display": "Place of death" }

]
},
"valueCodeableConcept": {
"coding": [

{ "system": "http://snomed.info/sct", "code": "16983000", "display": "Death in hospital" }

]
}
}
]
}
}
```
3) Certifier is empty and unnecessary. The instance and all references to it can be dropped.
4) Place of Death should be Location of death
5) The display value of "Certifying physician-To the best of my knowledge, death occurred due to the cause(s) and manner stated." should be "Death certification by physician (procedure)"
6) Many of the race/ethnicity display names are off, they should match the values in the IG
[Twila-Hilty-Example.txt](https://github.com/nightingaleproject/vrdr-dotnet/files/10439164/Twila-Hilty-Example.txt)

**Comment by johnarleyburns** [comment]
As per conversation with MITRE, dropping Patient.gender change, DeathCertificate.date change, and empty Certifier change.
