### ISSUE TITLE
Update vrdr dotnet README to describe the annotations in DeathRecord.cs

### ISSUE THREAD

**Issue by pkmitre** [nightingaleproject/vrdr-dotnet#360]
Explain how the DeathRecord.cs annotations work and what the attributes each mean. this should be added to the existing README in a new "For Library Developers" section just before the licensing.

Example of the annotations in question: https://github.com/nightingaleproject/vrdr-dotnet/blob/master/VRDR/DeathRecord_submissionProperties.cs#L43-L44

These system attributes are defined here: https://github.com/nightingaleproject/vrdr-dotnet/blob/master/VRDR/DeathRecord_util.cs#L1017-L1118

One example of how these attributes are used is here: https://github.com/nightingaleproject/vrdr-dotnet/blob/master/VRDR.CLI/Program.cs#L479-L489

These are also used in Canary, e.g., here: https://github.com/nightingaleproject/vrdr-dotnet/blob/master/VRDR.CLI/Program.cs#L479-L489

**Comment by johnarleyburns** [comment]
Be sure to also update the contact email to NVSSModernization (CDC) <nvssmodernization@cdc.gov>.
