### ISSUE TITLE
Create tests for vrdr-dotnet date part absent edge cases

### ISSUE THREAD

**Issue by pkmitre** [nightingaleproject/vrdr-dotnet#361]
Additional tests should be added to make sure there are no remaining edge cases. Tests should exercise IJE to FHIR and FHIR to IJE

* No date part absent
* All date part absent
* Year absent
* Month absent
* Day absent
* Year & month
* Year & day
* Month & day

Some of the existing tests can be seen at https://github.com/nightingaleproject/vrdr-dotnet/blob/master/VRDR.Tests/DeathRecord_Should.cs#L3008-L3071

**Comment by johnarleyburns** [comment]
Updated as part of Date of Death Pronounced changes.
