### ISSUE TITLE
Display Strings in RaceAndEthnicity.cs / NvssRace and NvssEthnicity are Incorrect

### ISSUE THREAD

**Issue by saulakravitz** [nightingaleproject/vrdr-dotnet#369]
The display strings are all like "HispanicCuban" instead of "Hispanic Cuban".
This problem is in both NvssRace and NvssEthnicity.

The display string for AmericanIndianOrAlaskanNative should be:  "American Indian Or AlaskaNative".  (ALaska, not Alaskan).

**Comment by johnarleyburns** [comment]
Incorporated into fixes for Issue 359, so closing this.
