### ISSUE TITLE
Fix Regexp for ICD10 Codes in VRDR .NET Library

### ISSUE THREAD

**Issue by saulakravitz** [nightingaleproject/vrdr-dotnet#373]
The Regexp for ICD10 codes doesn't allow a U as first character -- "^[A-TV-Z][0-9][0-9AB][0-9A-TV-Z]{0,2}$"

That appears to be a bug -- https://www.icd10data.com/ICD10CM/Codes/U00-U85

The same is true for the subsequent alpha characters in the ICD10 code, and that is worth checking.

**Comment by johnarleyburns** [comment]
NOTE: method to fix is in class:

IJEMortality.cs

Method which needs to be fixed is:

ValidNCHSICD10(string nchsicd10code)

A new test case should be added as a new test method in class:

MortalityData_Should.cs

Specific codes which should match as valid in the test case (one method call per test case) is:

U071
A379
G309
J189
