### ISSUE TITLE
Update xml and json examples to have correct case-sensitive Structure Definitions for the VRDR IG and VRDR Messaging IG

### ISSUE THREAD

**Issue by johnarleyburns** [nightingaleproject/vrdr-dotnet#376]

**Comment by johnarleyburns** [comment]
NOTE: fixes have been made in VRDR Java Library, so similar changes should be made in VRDR dotnet library.

**Comment by johnarleyburns** [comment]
Unix command line (can run in Windows Subsystem Linux with gnu grep):

grep -ir -C 2 profile VRDR.Tests/fixtures

**Comment by johnarleyburns** [comment]
Example that is incorrect:

VRDR.Tests/fixtures//json/RaceEthnicityCaseRecord3.json-            "http://hl7.org/fhir/us/vrdr/StructureDefinition/VRDR-Decedent-Mother"

Whereas the VRDR IG shows:

http://build.fhir.org/ig/HL7/vrdr/branches/master/StructureDefinition-vrdr-decedent-mother.html

**Comment by consultantusa** [comment]
Closed as approved https://github.com/nightingaleproject/vrdr-dotnet/pull/434
