### ISSUE TITLE
DemographicsCodingMessage.Parse fails

### ISSUE THREAD

**Issue by trevor-webster** [nightingaleproject/vrdr-dotnet#523]
When trying 

`var message = DemographicsCodingMessage.Parse(GetStream("demographics.json"));`

the error shown is 
```

Message: 
System.ArgumentException : Type checking the data: Encountered unknown element 'fullUrl' at location 'Bundle.fullUrl[0]' while parsing

  Stack Trace: 
BaseMessage.ParseJSON(String content, Boolean permissive) line 706
BaseMessage.ParseGenericBundle(String source, Boolean permissive) line 502
BaseMessage.Parse(String source, Boolean permissive) line 470
BaseMessage.Parse(StreamReader source, Boolean permissive) line 583
VDH_IJE_Tests.CreateAcknowledgement() line 51
```
[demographics.txt](https://github.com/nightingaleproject/vrdr-dotnet/files/12753002/demographics.txt)

The attached was taken from 
https://apigw.cdc.gov/OSELS/NCHS/NVSSFHIRAPI/VT/Bundles?_since=

**Comment by whichwit** [comment]
Thanks for the submission Trevor. The message to be parsed is not a well-formed FHIR message. If this is a direct response from NVSS API I need to inquire them. A few changes I can suggest in the meantime:

- There is this mention: `Please note that paging should be used without using the _since parameter, which is intended for use during development but not during testing.`. It may be worth a try without it.
- `Bundles` is phased out, `Bundle` is the better one to use.

If you can give the above mentions a try, they may help. More updates to come.
