### ISSUE TITLE
IJEMortality.DateTime_Set throws error when passed value is a leap day (ie: 02/29/2024)

### ISSUE THREAD

**Issue by ewonggpts** [nightingaleproject/vrdr-dotnet#567]
We're encountering an error when trying to initiate a new IJEMortality class by passing in an IJE string, when one of the date fields is in a leap year:
`IJEMortality ije = new IJEMortality(ijeString);`
Exception details:
`Exception Type: System.ArgumentOutOfRangeException
Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond)
   at System.DateTimeOffset..ctor(Int32 year, Int32 month, Int32 day, Int32 hour, Int32 minute, Int32 second, Int32 millisecond, TimeSpan offset)
   at VRDR.IJEMortality.DateTimeStringHelper(IJEField info, String value, String type, DateTimeOffset date, Boolean dateOnly, Boolean withTimezoneOffset)
   at VRDR.IJEMortality.DateTime_Set(String ijeFieldName, String dateTimeType, String fhirFieldName, String value, Boolean dateOnly, Boolean withTimezoneOffset)
   at VRDR.IJEMortality.set_CERTDATE(String value)`

Upon investigation the IJEMortality class...it looks like when the DateTimeStringHelper method is executed, it sets the date DateTimeOffset class in pieces (Month first, then Day, then Year):
`case "MMddyyyy":
                    {
                        if (value == null || value.Length < 8)
                        {
                            return "";
                        }

                        if (int.TryParse(Truncate(value, info.Length).Substring(0, 2), out var result) && result != 99)
                        {
                            date = new DateTimeOffset(date.Year, result, date.Day, date.Hour, date.Minute, date.Second, date.Millisecond, TimeSpan.Zero);
                        }

                        if (int.TryParse(Truncate(value, info.Length).Substring(2, 2), out var result2) && result2 != 99)
                        {
                            date = new DateTimeOffset(date.Year, date.Month, result2, date.Hour, date.Minute, date.Second, date.Millisecond, TimeSpan.Zero);
                        }

                        if (int.TryParse(Truncate(value, info.Length).Substring(4, 4), out var result3) && result3 != 9999)
                        {
                            date = new DateTimeOffset(result3, date.Month, date.Day, date.Hour, date.Minute, date.Second, date.Millisecond, TimeSpan.Zero);
                        }

                        break;
                    }`

if the passed "date" param isn't on a leap year, and the passed "value" param is.  It'll throw an error when trying to set the new Month, then Date, because the old Year isn't a leap year.

**Comment by whichwit** [comment]
After given it more thought and checking throughout other parts of the library, the error is appropriate that an input value like "2021-02-29" is an invalid date.

For WY's purpose, what would be the desired behavior? A few suggestions are:

- ignore the value (silently fail)
- default to the last day of the month (silently correct)
- throw an error so the source data can be corrected (current behavior)

**Comment by ewonggpts** [comment]
We encountered the error when we passed in an actual leap day - "2024-02-29". We should expect the library to be able to consume this date.
