### ISSUE TITLE
Using FHIR data type Coding

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#69]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/MortalityData.cs#L468

Suggest to use FHIR build-in Coding type instead of generic Tuple class.

It looks like:
```
public List<Coding> CdcRaceAianCodes = 
{
    new Coding("urn:oid:2.16.840.1.113883.6.238", "1002-5", "American Indian or Alaska Native"),
    ......
}
```

And the search of the list looks lik
```
public string AianRaceCodeToRaceName(string code)
{
    return CdcRaceAianCodes.FirstOrDefault(c => c.Code == code);
}

public string AIANRaceNameToRaceCode(string name)
{
    return CdcRaceAianCodes.FirstOrDefault(c => c.Display == name)
}
```

**Comment by holmesie** [comment]
Yes this is definitely something I thought of early on, but we'd like to keep this library as agnostic as possible of any underlying dependencies - if needed we'd like to keep the ability to replace the underlying functionality of going to/from FHIR - which I think is best achieved by sticking to native types.

**Comment by yunwwang** [comment]
if not FHIR Coding type, at least create a Local data class, such as MyCoding with two properties: Code and Display (or Text). Tuple is convenient for temporary data transfer but it is not good for persistent data storage and operation
