### ISSUE TITLE
Move all codes to its own file

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#70]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/MortalityData.cs#L468

I would move the content of coding to a separate json file. So that it is easy to maintain the content and reduce the size of this class. 

Normally it is hard to navigate a class if it is more than 250 lines

**Comment by holmesie** [comment]
Right, agreed. How would loading from a JSON file work in a distributed library?
