### ISSUE TITLE
What's the pattern for using Instance?

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#71]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/MortalityData.cs#L13

The caller can always just say 
```
var mData = new MotalityData()
```

**Comment by holmesie** [comment]
Ideas for avoiding this? We definitely want the least memory impact here... But we need these extensive lookups. I went for a singleton pattern here.
