### ISSUE TITLE
Consider using FHIR Address data type

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#73]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/MortalityData.cs#L1863

Instead of using Tuple, consider using Address data type from FHIR

http://build.fhir.org/datatypes.html#Address

**Comment by holmesie** [comment]
Similar to another response - Yes this is definitely something I thought of early on, but we'd like to keep this library as agnostic as possible of any underlying dependencies - if needed we'd like to keep the ability to replace the underlying functionality of going to/from FHIR - which I think is best achieved by sticking to native types.

**Comment by yunwwang** [comment]
The same. My concern is not using FHIR data type or not but using Tuple. Let's create a local class for this data model

**Comment by holmesie** [comment]
On further thought, totally agree with this.
