### ISSUE TITLE
Private member variable shall be camel case

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#74]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/DeathRecord.cs#L23

private member variables shall be camel case. For example
```
private Organization interestedParty;
```

Another choice, which also popular, is to turn member variable to member property, such as
```
private Organization InterestedParty {get; set;}
```
Advantage for member property is easily converting between public and private property.

**Comment by holmesie** [comment]
Okay, lets chat about this.
