### ISSUE TITLE
Use Object initializer

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#75]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/DeathRecord.cs#L153

Like
```
Bundle = new Bundle
{
    Id = Guid.NewGuid().ToString(),
    ......
};
```

**Comment by holmesie** [comment]
Yes, great point!
