### ISSUE TITLE
Split to FromXml() and FromJson()

### ISSUE THREAD

**Issue by yunwwang** [nightingaleproject/vrdr-dotnet#76]
https://github.com/nightingaleproject/vrdr-dotnet/blob/f9aade296508062bc34d89f6acc0f86e51f441a7/FhirDeathRecord/DeathRecord.cs#L281

Instead of put xml and json parsing together, split them to two methods. One for parsing xml and another one for parsing json

**Comment by holmesie** [comment]
What about Turtle? I'd prefer a constructor that can handle strings of any type. Do you mean sub-methods to handle the specific use-cases (xml vs json)?

**Comment by holmesie** [comment]
On further thought, we should definitely have FromXml and FromJson methods - even if just helpers. We definitely still need to keep a constructor that can handle anything valid (if possible).

**Comment by yunwwang** [comment]
In most situation, the input format is identified before calling constructor. For example, for CLI, the file type is known from the file name. For Web API, the content type is known from the content header. So it is very rare for an internal logic to detect the content type. I don't mind to keep this constructor and call FromXml/Json/Turtle inside.
